config/routes.rb
Rails.application.routes.draw do

  get 'orders/index'
  get 'orders/show'

  get 'pages/show'

  get "search", to: "movies#search", as: "search" # search_path
  get 'movies/cart', to: 'movies#cart', as: 'cart'
  post 'movies/add_to_cart/:id', to: 'movies#add_to_cart', as: 'add_to_cart'
  post 'movies/increase_quantity/:id', to: 'movies#increase_quantity', as: 'increase_quantity'
  post 'movies/decrease_quantity/:id', to: 'movies#decrease_quantity', as: 'decrease_quantity'
  delete 'movies/remove_from_cart/:id/:route', to: 'movies#remove_from_cart', as: 'remove_from_cart'
  delete 'movies/delete_cart', to: 'movies#delete_cart', as: 'delete_cart'

  scope 'checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create' # CAN USE :id PARAMS FOR THIS
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  root to: 'movies#index'
  resources 'movies', only: %i[index show]

  devise_for :customers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get ':permalink', to: 'pages#show', as: 'show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :initialize_session

  def index
    @movies = Movie.all.page(params[:page])
    @genres = Genre.all
  end

  def show
    @movie = Movie.includes(:genres).find(params[:id])
  end

  def search
    genre_id = params[:genre_id]
    search_title = params[:title]
    if genre_id.blank?
      @movies = Movie.where("title LIKE ?", "%#{params[:title].downcase}%").page(params[:page])
    else
      @movies = Movie.joins(:genres).where("title LIKE ? AND genres.id = ?", "%#{params[:title]}%", params[:genre_id]).page(params[:page])
    end
    @genres = Genre.all
  end

  def cart
  end

  def add_to_cart
    if current_customer
      id = params[:id].to_i
      session[:cart][id] = 1 unless session[:cart].include?(id)
      redirect_to root_path
    else
      redirect_to new_customer_session_path
    end
  end
  # No associated view. Redirects back to index.

  def remove_from_cart
    id = params[:id]
    route = params[:route]
    session[:cart].delete(id)
    if route == "cart"
      redirect_to cart_path
    elsif route == "home"
      redirect_to root_path
    end
  end

  def delete_cart
    session[:cart] = nil
    redirect_to root_path
  end

  def increase_quantity
    id = params[:id]
    current_quantity = session[:cart].fetch(id)
    updated_movie = { id => current_quantity += 1 }
    session[:cart].merge!(updated_movie)
    redirect_to cart_path
  end
  # No associated view. Redirects back to index.

  def decrease_quantity
    id = params[:id]
    current_quantity = session[:cart].fetch(id)
    if current_quantity > 1
      updated_movie = { id => current_quantity -= 1 }
      session[:cart].merge!(updated_movie)
    end
    redirect_to cart_path
  end
  # No associated view. Redirects back to index.

  private

  def initialize_session
    session[:cart] ||= {} # Empty cart is an empty hash.
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_movie.html.erb
<div class="col s6 m4 l3">
  <div class="card" style="height: 630px">
    <div class="card-image waves-block waves-light">
      <% unless session[:cart].include?(movie.id.to_s) %>
        <%= link_to '<i class="material-icons">add_shopping_cart</i>'.html_safe, 
            add_to_cart_path(movie.id),
            class: "btn-floating halfway-fab waves-effect waves-light red",
            method: :post %>
      <% else %>
        <%= link_to '<i class="material-icons">remove_shopping_cart</i>'.html_safe, 
            remove_from_cart_path(movie.id, "home"),
            class: "btn-floating halfway-fab waves-effect waves-light blue",
            method: :delete %>
      <% end %>
      <img class="activator" src="<%= movie.poster %>">
    </div>
    <div class="card-content">
      <div class="row">
        <span class="card-title activator grey-text text-darken-4">
          <div class="col s12 m10 l10">
            <%= movie.title %>
          </div>
          <div class="col s12 m2 l2">
            <i class="material-icons right">
              more_vert
            </i>
          </div>
        </span>
      </div>
      <div class="card-action" style="position: absolute; bottom: 5px; right: 5px;">
        <b>
          <%= number_to_currency movie.price / 100.0 %>
        </b>
      </div>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">
        <%= movie.title %><i class="material-icons right">close</i>
      </span>
      <p>
        <i>
          <%= movie.description %>
        </i>
      </p>
      <p>
        <%= movie.release_date.strftime("%B %d, %Y") %>
      </p>
      <div>
        <%= link_to "View", movie, class: 'waves-effect waves-light btn' %>
        <% unless session[:cart].include?(movie.id.to_s) %>
          <%= link_to '<i class="material-icons">add_shopping_cart</i>'.html_safe, 
              add_to_cart_path(movie.id),
              class: "btn halfway-fab waves-effect waves-light red",
              method: :post %>
        <% else %>
          <%= link_to '<i class="material-icons">remove_shopping_cart</i>'.html_safe, 
              remove_from_cart_path(movie.id, "home"),
              class: "btn halfway-fab waves-effect waves-light blue",
              method: :delete %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/movies/_search_form.html.erb
<%= form_with(url: search_path, local: true, method: "get", class: 'search-form') do %>
  <div class="field has-addons">
    <div class="control">
      <div class="col s12 m5 l5">
        <%= text_field_tag(:title, nil, class: 'input', placeholder: 'Title') %>
      </div>
    </div>
    <div class="control">
      <div class="col s10 m5 l5">
        <%= select_tag(:genre_id, options_from_collection_for_select(@genres, "id", "name", params[:genre_id]), include_blank: "Any", class: 'form-control') %>
      </div>
    </div>
    <div class="control">
      <div class="col s2 m2 l2">
        <%= button_tag(type: "submit", class: "btn btn-default") do %>
            <i class="material-icons">search</i>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/movies/cart.html.erb
<h5>Shopping Cart (<%= @cart.size %>)</h5>
<table class="highlight" style="margin-bottom: 20px">
  <thead>
    <tr>
      <th>Product Details</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% @cart.each do |cart_item| %>
    <tr>
      <td>
        <div class="row">
          <div class="col">
            <img src="<%= cart_item.poster %>" alt="<%= cart_item.title %>">
          </div>
          <div class="col s6">
            <div style="padding-bottom: 15px"><%= link_to "<b>#{cart_item.title}</b>".html_safe, cart_item %></div>
            <div style="padding-bottom: 15px"><%= cart_item.release_date.strftime("%B %d, %Y") %></div>
            <div style="padding-bottom: 15px"><%= cart_item.length %> mins</div>
          </div>
        </div>
      </td>
      <td>
        <%= link_to '<i class="material-icons">add</i>'.html_safe, 
            increase_quantity_url(cart_item), 
            class: 'btn-floating btn-small waves-effect waves-light green', 
            method: :post %>

        <b><%= session[:cart].fetch(cart_item.id.to_s) %></b>

        <%= link_to '<i class="material-icons">remove</i>'.html_safe, 
            decrease_quantity_url(cart_item), 
            class: 'btn-floating btn-small waves-effect waves-light red', 
            method: :post unless session[:cart].fetch(cart_item.id.to_s) == 1 %><br>
        
        <div style="padding-top: 10px">
          <%= link_to 'Remove',
              remove_from_cart_path(cart_item, "cart"),
              class: 'waves-effect waves-light btn-small',
              method: :delete %>
        </div>
      </td>
      <td><%= number_to_currency cart_item.price / 100.0 %></td>
      <td><%= number_to_currency cart_item.price * session[:cart].fetch(cart_item.id.to_s) / 100.0 %></td>
    </tr>
  <% end %> 
  </tbody>
</table>
  <div style="float: right; padding-bottom: 25px">
    <div class="row">
      <div class="col s7">
        <%= link_to "Remove All", delete_cart_path, 
            class: "red waves-effect waves-light btn",
            method: :delete unless @cart.size == 0 %>
      </div>
      <div class="col s5">
        <%= button_to "Checkout", checkout_create_path, 
            class: "waves-effect waves-light btn",
            remote: true unless @cart.size == 0 %>
      </div>
    </div>
  </div>

app/views/movies/index.html.erb
<div class="row" style="margin-top: 50px">
  <%= paginate @movies %>
  <h5 style="text-align: center">Search movies by genre:</h5>
  <%= render 'movies/search_form' %>
</div>

<div class="row">
  <% @movies.each do |movie| %>
    <%= render partial: 'movie',
              object: movie,
              locals: { show_link: false } 
    %>
  <% end %>
</div>

app/views/movies/search.html.erb
<div class="row" style="margin-top: 50px">
  <%= paginate @movies %>
  <h5 style="text-align: center">Search movies by genre:</h5>
  <%= render 'movies/search_form' %>
</div>

<p>
  Found <%= pluralize(@movies.size, 'result') %>.
</p>

<div class="row">
  <%= render partial: 'movies/movie',
             collection: @movies,
             locals: { show_link: true } %>
</div>

app/views/movies/show.html.erb
<div class="row">
  <div class="movie-card-title">
    <h3 class="movie-title-show"><%= @movie.title %></h3>
  </div>
  <div class="col s12 m5 l3">
    <div class="card">
      <div class="card-image">
        <img src="<%= @movie.poster %>" alt="<%= @movie.title %>">
        <% unless session[:cart].include?(@movie.id.to_s) %>
          <%= link_to '<i class="material-icons">add_shopping_cart</i>'.html_safe, add_to_cart_path(@movie.id), method: :post,
          class: "btn-floating halfway-fab waves-effect waves-light red"%>
        <% else %>
          <%= link_to '<i class="material-icons">remove_shopping_cart</i>'.html_safe, remove_from_cart_path(@movie.id, "home"), method: :delete,
          class: "btn-floating halfway-fab waves-effect waves-light blue"%>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col s12 m5 l9">
    <table class="movie-table">
      <thead>
        <tr>
          <th>Release Date</th>
          <th>Length</th>
          <th>Producers</th>
          <th>Genres</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="movie-table-data"><%= @movie.release_date.strftime("%B %d, %Y") %></td>
          <td class="movie-table-data"><%= @movie.length %> minutes</td>
          <td class="movie-table-data">
            <% @movie.producers.each do |producer| %>
              <%= producer.name %>,
            <% end %>
          </td>
          <td class="movie-table-data">
            <% @movie.genres.each do |genre| %>
              <%= genre.name %>,
            <% end %>
          </td>
        </tr>
      <tbody>
    </table>
  </div>
  <div class="row">
    <div class="col s12 m12 l8">
    <p><%= @movie.description %></p>
  </div>
  <div class="row">
    <div class="col s3 offset-s">
    <h5>
      Price: 
      <%= number_to_currency @movie.price / 100.0 %>
    </h5>
  </div>
</div>