config/routes.rb
Rails.application.routes.draw do

  get 'orders/index'
  get 'orders/show'

  get 'pages/show'

  get "search", to: "movies#search", as: "search" # search_path
  get 'movies/cart', to: 'movies#cart', as: 'cart'
  post 'movies/add_to_cart/:id', to: 'movies#add_to_cart', as: 'add_to_cart'
  post 'movies/increase_quantity/:id', to: 'movies#increase_quantity', as: 'increase_quantity'
  post 'movies/decrease_quantity/:id', to: 'movies#decrease_quantity', as: 'decrease_quantity'
  delete 'movies/remove_from_cart/:id/:route', to: 'movies#remove_from_cart', as: 'remove_from_cart'
  delete 'movies/delete_cart', to: 'movies#delete_cart', as: 'delete_cart'

  scope 'checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create' # CAN USE :id PARAMS FOR THIS
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  root to: 'movies#index'
  resources 'movies', only: %i[index show]

  devise_for :customers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get ':permalink', to: 'pages#show', as: 'show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :movie_orders
  has_many :movies, through: :movie_orders

  validates :reference_number, uniqueness: true
  validates :reference_number, :subtotal,
            :total, :address, :order_status, presence: true

  def display_name
    reference_number # or whatever column you want
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    if current_customer
      @orders = Order.all
    else
      redirect_to root_path
    end
  end

  def show
    if current_customer
      @order = Order.includes(:movie_orders).find(params[:id])
    else
      redirect_to root_path
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<table class="striped">
  <thead>
    <tr>
      <th>Reference Number:</th>
      <th>Pst Rate</th>
      <th>Gst Rate</th>
      <th>Hst Rate</th>
      <th>Subtotal</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to "#{order.reference_number }", orders_show_path(order), method: :post %></td>
        <td><%= order.pst_rate %></td>
        <td><%= order.gst_rate %></td>
        <td><%= order.hst_rate %></td>
        <td><%= number_to_currency order.subtotal / 100.0 %></td>
        <td><%= number_to_currency order.total / 100.0 %></td>
      </tr>
    <% end %>
    
  </tbody>
</table>
            

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>