config/routes.rb
Rails.application.routes.draw do

  get 'orders/index'
  get 'orders/show'

  get 'pages/show'

  get "search", to: "movies#search", as: "search" # search_path
  get 'movies/cart', to: 'movies#cart', as: 'cart'
  post 'movies/add_to_cart/:id', to: 'movies#add_to_cart', as: 'add_to_cart'
  post 'movies/increase_quantity/:id', to: 'movies#increase_quantity', as: 'increase_quantity'
  post 'movies/decrease_quantity/:id', to: 'movies#decrease_quantity', as: 'decrease_quantity'
  delete 'movies/remove_from_cart/:id/:route', to: 'movies#remove_from_cart', as: 'remove_from_cart'
  delete 'movies/delete_cart', to: 'movies#delete_cart', as: 'delete_cart'

  scope 'checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create' # CAN USE :id PARAMS FOR THIS
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  root to: 'movies#index'
  resources 'movies', only: %i[index show]

  devise_for :customers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get ':permalink', to: 'pages#show', as: 'show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :province
  has_many :orders

  validates :email, :address, uniqueness: true
  # validates :address, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie_genres
  has_many :movies, through: :movie_genres

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :movie_orders
  has_many :movie_genres
  has_many :movie_producers
  has_many :orders, through: :movie_orders
  has_many :genres, through: :movie_genres
  has_many :producers, through: :movie_producers

  accepts_nested_attributes_for :movie_orders, allow_destroy: true
  accepts_nested_attributes_for :movie_genres, allow_destroy: true
  accepts_nested_attributes_for :movie_producers, allow_destroy: true

  validates :imdb_number, uniqueness: true
  validates :imdb_number, :title, :description, :price, presence: true
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/movie_order.rb
class MovieOrder < ApplicationRecord
  belongs_to :movie
  belongs_to :order

  validates :quantity, :movie_price, presence: true
end

app/models/movie_producer.rb
class MovieProducer < ApplicationRecord
  belongs_to :movie
  belongs_to :producer
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :movie_orders
  has_many :movies, through: :movie_orders

  validates :reference_number, uniqueness: true
  validates :reference_number, :subtotal,
            :total, :address, :order_status, presence: true

  def display_name
    reference_number # or whatever column you want
  end
end

app/models/page.rb
class Page < ApplicationRecord
  validates :permalink, uniqueness: true
  validates :title, :permalink, presence: true
end

app/models/producer.rb
class Producer < ApplicationRecord
  has_many :movie_producers
  has_many :movies, through: :movie_producers

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, :pst_rate, :gst_rate, :hst_rate, presence: true
  has_many :customers

  has_one_attached :image
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :initialize_session

  def index
    @movies = Movie.all.page(params[:page])
    @genres = Genre.all
  end

  def show
    @movie = Movie.includes(:genres).find(params[:id])
  end

  def search
    genre_id = params[:genre_id]
    search_title = params[:title]
    if genre_id.blank?
      @movies = Movie.where("title LIKE ?", "%#{params[:title].downcase}%").page(params[:page])
    else
      @movies = Movie.joins(:genres).where("title LIKE ? AND genres.id = ?", "%#{params[:title]}%", params[:genre_id]).page(params[:page])
    end
    @genres = Genre.all
  end

  def cart
  end

  def add_to_cart
    if current_customer
      id = params[:id].to_i
      session[:cart][id] = 1 unless session[:cart].include?(id)
      redirect_to root_path
    else
      redirect_to new_customer_session_path
    end
  end
  # No associated view. Redirects back to index.

  def remove_from_cart
    id = params[:id]
    route = params[:route]
    session[:cart].delete(id)
    if route == "cart"
      redirect_to cart_path
    elsif route == "home"
      redirect_to root_path
    end
  end

  def delete_cart
    session[:cart] = nil
    redirect_to root_path
  end

  def increase_quantity
    id = params[:id]
    current_quantity = session[:cart].fetch(id)
    updated_movie = { id => current_quantity += 1 }
    session[:cart].merge!(updated_movie)
    redirect_to cart_path
  end
  # No associated view. Redirects back to index.

  def decrease_quantity
    id = params[:id]
    current_quantity = session[:cart].fetch(id)
    if current_quantity > 1
      updated_movie = { id => current_quantity -= 1 }
      session[:cart].merge!(updated_movie)
    end
    redirect_to cart_path
  end
  # No associated view. Redirects back to index.

  private

  def initialize_session
    session[:cart] ||= {} # Empty cart is an empty hash.
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find_by(permalink: params[:permalink])

    redirect_to root_path if @page.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shopping_cart_helper.rb
module ShoppingCartHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
  <%= link_to "Movies R Us", root_path, class: "brand-logo" %>
    <a href="" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to "About", "/about" %></li>
      <li><%= link_to "Contact", "/contact" %></li>
      <% if current_customer %>
        <li><%= link_to "Sign out", destroy_customer_session_path, method: :delete %></li>
        <% if current_customer.name.blank? %>
          <li><b>Welcome, <%= current_customer.email %></b></li>
        <% else %>
          <li><b>Welcome, <%= current_customer.name %></b></li>
        <% end %>
        <li>
          <%= link_to '<i class="material-icons">shopping_cart</i>'.html_safe, cart_path,
            class: "btn-floating waves-effect waves-light red"%><br>
        </li>
        <li>
          <div class="cart-badge">
            <h6><%= @cart.size %></h6>
          </div>
        </li>
      <% else %>
        <li><%= link_to "Sign in", new_customer_session_path  %></li>
      <% end %>
    </ul>
  </div>
</nav>

<ul class="sidenav" id="mobile-demo">
  <li>
    <% if current_customer %>
      <div class="user-view">
        <a href=""><span class="black-text name"><%= current_customer.name %></span></a>
        <a href=""><span class="black-text email"><%= current_customer.email %></span></a>
      </div>
      <%= link_to "Cart [#{@cart.size}]", cart_path %>
    <% end %>
  </li>
  <li><div class="divider"></div></li>
  <li><%= link_to "About", "/about" %></li>
  <li><%= link_to "Contact", "/contact" %></li>
  <% if current_customer %>
    <li><%= link_to "Sign out", destroy_customer_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Sign in", new_customer_session_path  %></li>
  <% end %>
</ul>

app/views/layouts/_search.html.erb
<nav>
  <div class="nav-wrapper">
    <form>
      <div class="input-field">
        <input id="search" type="search" required>
        <label class="label-icon" for="search"><i class="material-icons">search</i></label>
        <i class="material-icons">close</i>
      </div>
    </form>
  </div>
</nav>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesRUsEcommerce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>      
  </head>

  <body>
    <div class="container">
      <%= render partial: 'layouts/navbar',
          object: @cart %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/show.html.erb
<h3>
  <%= @page.title %>
</h3>

<p>
  <%= @page.content %>
</p>